<?php
include("../includes/conn.php");
include("../includes/extraer_variables_seg.php");
include("auto.php");

function verificaremail($email){ 
  /*if (!ereg("^([a-zA-Z0-9._]+)@([a-zA-Z0-9.-]+).([a-zA-Z]{2,4})$",$email)){ 
      return FALSE; 
  } else { 
       return TRUE; 
  } */
  
  return filter_var($email, FILTER_VALIDATE_EMAIL);
}








$uploadDir = '/control_admin/uploads/';



function errorHandler($errno, $errstr, $errfile, $errline) {
	// In this script, the silently suppress any error generated by getimagesize
	// which will throw an error if the "image" isn't an image
	// ie doesn't have a valid width / height

    /* Don't execute PHP internal error handler */
    return true;
}

$old_error_handler = set_error_handler("errorHandler");

// Check if the file has a width and height


if (!empty($_FILES)) {

	$fileData = $_FILES['Filedata'];
	
	$result1ey = mysql_query("SELECT id FROM com_csv ORDER BY id DESC LIMIT 1",$link) or die("el error es porque: ".mysql_error());
               if(mysql_num_rows($result1ey)==0) { 
                   $id_csv = 1;
               }
                else {
                  $rowe = mysql_fetch_array($result1ey);
                  $id_csv = $rowe['id'] + 1;
                }
				
				

	if ($fileData) {
		$tempFile   = $fileData['tmp_name'];
		$uploadDir  = $_SERVER['DOCUMENT_ROOT'] . $uploadDir;
		$targetFile = $uploadDir . $id_csv. "_". $fileData['name'];

		// Validate the file type
		$fileTypes = array('csv'); // Allowed file extensions
		$fileParts = pathinfo($fileData['name']);

		// Validate the filetype
		if (in_array(strtolower($fileParts['extension']), $fileTypes) && filesize($tempFile) > 0) {
			
			$result00 = mysql_query ("INSERT INTO com_csv (id, codigo, user, fecha, evento, ip) VALUES ('".$id_csv."','".$targetFile."','".$rowff['id']."','".$fechoy."','".$evento."','".getRealIP()."')",$link) or die("el error es en el insert csv: ".mysql_error());
			
			// Save the file
			move_uploaded_file($tempFile, $targetFile);
			
			
			$archivo = file_get_contents($targetFile);
            $comas = substr_count($archivo, ',');
            $punto = substr_count($archivo, ';');
            if ($comas >= $punto) {
	          $separador = ","; 
            } else {
              $separador = ";"; 
            }
			
			// empieza a leer el archivo
			
			
			$fp = fopen ($targetFile , "r" ); 
			$j = 1;
			$leyenda_error = "";
            while (( $data = fgetcsv( $fp , 1000 , $separador )) !== FALSE ) {

               $i = 0; 
			   $error = 0;
			   $errordes = "";
			   $campos = "";
			   $valores = "";
			   $camposd = "";
			   $email = "";
			   $nombre = "";
			   $delegado = "";
               foreach($data as $row) {
				   switch ($i):
                     case 0:
                      $columna = "email";
					  $columnad = "Email";
					  $email = $row;
					  if (!empty($row)) {
					    if (!verificaremail($row)) {
						  $error = 1;
						  $errordes .= "Email no valido, ";
						}
						$result1eB = mysql_query("SELECT * FROM com_alumnos WHERE email = '".$row."' LIMIT 1") or die("el error es porque: ".mysql_error());
                        if(mysql_num_rows($result1eB)>0) { 
						  $error = 1;
						  $errordes .= "Email YA EXISTE EN LA BASE DE DATOS, ";
						
			            }
					  } else {
						 $error = 1;
						 $errordes .= "El email no puede ser vacio, "; 
						 }
                      break;
					  case 1:
                      $columna = "nombre";
					  $columnad = "Nombre";
					  $nombre = $row;
					  if (empty($row)) {
						  $error = 1;
						  $errordes .= "Nombre no puede ser vacio, ";
					  }
					  
                      break;
                    
                    case 2:
                     $columna = "apellido";
					  $columnad = "Apellido";
					  if (empty($row)) {
						  $error = 1;
						  $errordes .= "Apellido no puede ser vacio, ";
					  }
					  $apellido = $row;
					 
                      break;
					  
					  case 3:
                     $columna = "delegado";
					  $columnad = "Delegado";
					  if (empty($row)) {
						  $error = 1;
						  $errordes .= "Delegado no puede ser vacio, ";
					  }
					  
					  $sql_del = "SELECT * FROM com_users WHERE nombre_clave = '".addslashes(urls_amigables(utf8_encode($row)))."'";
		  // echo $sql_del;
          $result_del = mysql_query($sql_del);
		  if ($row_del = mysql_fetch_array($result_del)) {
			  $id_delegado = $row_del['id'];
			  }
			  
			else {
				$id_delegado = 0;
				$error = 1;
				$errordes .= "Delegado no coincide con ningun delegado registrado -".addslashes(urls_amigables(utf8_encode($row))) ;
			}
					 
                      break;
					
	
                    endswitch;

                 //echo "Campo $i: $row<br>"; // Muestra todos los campos de la fila actual 
                 $i++ ;
				 
				 

                }
				
				
				if ($error == 0) {
					
					
				$sql = "INSERT INTO com_invitados (email, evento, fecin, nombre, apellido, userin, invitacion, delegado) VALUES ('".$email."', '".$evento."', '".$fechoy."', '".utf8_encode($nombre)."', '".utf8_encode($apellido)."', '".$rowff['id']."', '0', '".$id_delegado."')";
				$sql1 .= "<br>".$sql;
				$resulte = mysql_query ($sql,$link) or die("error al insertar: ".mysql_error().$sql);
				
				/*  se inserta en los alumnos */
				$result1e = mysql_query("SELECT * FROM com_alumnos WHERE email = '".$email."' LIMIT 1") or die("el error es porque: ".mysql_error());
               if(mysql_num_rows($result1e)==0) { 
                  
               
				
			 
                 $result1ex = mysql_query("SELECT id FROM com_alumnos ORDER BY id DESC LIMIT 1",$link) or die("el error es porque46: ".mysql_error());
               if(mysql_num_rows($result1ex)==0) { 
                   $id = 1;
               }
                else {
                  $rowe = mysql_fetch_array($result1ex);
                  $id = $rowe['id'] + 1;
                }
				
				$clave00 = createhash($tokensArray,$hashLenght);
				$clave02 = createhash($tokensArray,$hashLenght);
				$usu_codigo = "asistente".$id;
				
				$sqlpi = "INSERT INTO com_alumnos (id, ape1, ape2, codusuario, email, nombre, dni, clave, fecha, pass, fecreg, origen) VALUES ('".$id."','".addslashes (utf8_encode($apellido))."','".addslashes (utf8_encode($ape2))."','".$usu_codigo."', '".$email."','".addslashes(utf8_encode($nombre))."','".addslashes ($dni)."','".$clave00."','".$fechoy."','123458','".$fechoy."','3')";
				$result = mysql_query ($sqlpi,$link) or die ("hay un error en la consulta");
				
				$sqlpf = "INSERT INTO com_alumnos_eventos (alumno, evento, delegado, delegado_campo, fecreg) VALUES ('".$id."','".$evento."','".$id_delegado."','".$row_del['nombre_clave']."', '".$fechoy."')";
				$result = mysql_query ($sqlpf,$link) or die ("hay un error en la consulta");


			
                      
 
 }
                else {
					
					$rowff1 = mysql_fetch_array($result1e);
					$sqlw_er = "SELECT * FROM com_alumnos_eventos WHERE alumno = ". $rowff1['id'] ." AND evento = ".$evento."";
					//echo $sqlw_er;
				    $resulter = mysql_query($sqlw_er,$link) or die("el error es porque41: ".mysql_error());
            // aqui va el codigo
			  if ($rower = mysql_fetch_array($resulter)){
				
				$sqlpf = "UPDATE com_alumnos_eventos SET alumno = '".$rowff1['id']."', evento = '".$evento."', delegado = '".$id_delegado."', delegado_campo = '".$row_del['nombre_clave']."', fecreg = '".$fechoy."' WHERE id = ".$rower['id'];
				//echo $sqlpf ;
				$result = mysql_query ($sqlpf,$link) or die ("hay un error en la consulta1");
				
			  } else {
				  $sqlpf = "INSERT INTO com_alumnos_eventos (alumno, evento, delegado, delegado_campo, fecreg) VALUES ('".$rowff1['id']."','".$evento."','".$id_delegado."','".$row_del['nombre_clave']."', '".$fechoy."')";
				$result = mysql_query ($sqlpf,$link) or die ("hay un error en la consulta1");
				}
     
                }


				
				
				/* termina de insertar en los alumnos */
				
				
				} else {
			    
				 $leyenda_error .= "Error(es) en la linea: ".$j. " (".$camposd."): ". $errordes."<br><br>";	
				}

//echo "<br><br>nn";
$j++ ;

}

$resulttt = mysql_query ("UPDATE com_csv SET comentarios = '". addslashes($leyenda_error) ."' WHERE id = ".$id_csv."",$link) or die("el error es en LA MODIF: ".mysql_error());			
 
fclose ( $fp ); 

			//termina de leer el archivo



			echo "<span class=\"azul\">Archivo cargado</span><br />";
			echo "<span class=\"roja\">".$leyenda_error."</span><br />";
			
		} else {

			// The file type wasn't allowed
			echo '<span class="roja">Tipo de Archivo invalido.</span>';
		}
	}
}
?>